.TH "Include/System/ Directory Reference" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/System/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLogger\&.h\fP"
.br
.ti -1c
.RI "file \fBMutex\&.h\fP"
.br
.RI "\fIPthread_mutex wrapper'\&. \fP"
.ti -1c
.RI "file \fBSemaphore\&.h\fP"
.br
.ti -1c
.RI "file \fBThread\&.h\fP"
.br
.RI "\fIA C++ \fBThread\fP Wrapper for the pthread lib You need to subclass it and redefine the run() method'\&. \fP"
.ti -1c
.RI "file \fBTime\&.h\fP"
.br
.RI "\fIget the system time \fP"
.ti -1c
.RI "file \fBTypes\&.h\fP"
.br
.RI "\fI\fBTypes\fP class'\&. \fP"
.in -1c
