.TH "Socket/ Directory Reference" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Socket/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTcpServer\&.cpp\fP"
.br
.RI "\fITcp server'\&. \fP"
.ti -1c
.RI "file \fBTcpSocket\&.cpp\fP"
.br
.RI "\fIC++ wrapper for the socket library'\&. \fP"
.in -1c
