.TH "System/Logger.cpp" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System/Logger.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <System/Logger\&.h>\fP
.br

.SH "Detailed Description"
.PP 
\fBVersion:\fP
.RS 4
1'\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
10/12/2011 16:31:37
.RE
.PP
\fBAuthor:\fP
.RS 4
Ben D'\&. (BD), dbapps2@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
