.TH "Logger" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logger\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP (string name)"
.br
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.ti -1c
.RI "ofstream & \fBlog\fP (string type, int indent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ofstream \fBm_out\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Logger::Logger (stringname)"
.SS "Logger::~Logger ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "std::ofstream & Logger::log (stringtype, intindent = \fC0\fP)"
.SH "Member Data Documentation"
.PP 
.SS "ofstream \fBLogger::m_out\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
