.TH "Include/System/Logger.h" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/System/Logger.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <System/Time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBVersion:\fP
.RS 4
1'\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
10/12/2011 16:31:37
.RE
.PP
\fBAuthor:\fP
.RS 4
Ben D'\&. (BD), dbapps2@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
