.TH "Mutex" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mutex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.RI "\fIConstructor'\&. \fP"
.ti -1c
.RI "int \fBlock\fP ()"
.br
.RI "\fIlocks the mutex'\&. \fP"
.ti -1c
.RI "int \fBtryLock\fP ()"
.br
.RI "\fIThe trylock() method locks mutex'\&. \fP"
.ti -1c
.RI "int \fBunlock\fP ()"
.br
.RI "\fIIf the current thread holds the lock on mutex, then the \fBunlock()\fP function unlocks mutex'\&. \fP"
.ti -1c
.RI "int \fBdestroy\fP ()"
.br
.RI "\fIThe \fBdestroy()\fP method frees the resources allocated for mutex'\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mutex::Mutex ()"
.PP
Constructor'\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Mutex::destroy ()"
.PP
The \fBdestroy()\fP method frees the resources allocated for mutex'\&. \fBReturns:\fP
.RS 4
If successful, \fBdestroy()\fP will return zero'\&. Otherwise, an error number will be returned to indicate the error'\&. 
.RE
.PP

.SS "int Mutex::lock ()"
.PP
locks the mutex'\&. If the mutex is already locked, the calling thread will block until the mutex becomes available'\&. 
.PP
\fBReturns:\fP
.RS 4
If successful, \fBlock()\fP will return zero'\&. Otherwise, an error number will be returned to indicate the error'\&. 
.RE
.PP

.SS "int Mutex::tryLock ()"
.PP
The trylock() method locks mutex'\&. If the mutex is already locked, trylock() will not block waiting for the mutex, but will return an error condition 
.PP
\fBReturns:\fP
.RS 4
If successful, trylock() will return zero'\&. Otherwise, an error number will be returned to indicate the error'\&. 
.RE
.PP

.SS "int Mutex::unlock ()"
.PP
If the current thread holds the lock on mutex, then the \fBunlock()\fP function unlocks mutex'\&. Calling \fBunlock()\fP with a mutex that the calling thread does not hold will result in undefined behavior'\&. 
.PP
\fBReturns:\fP
.RS 4
If successful, \fBunlock()\fP will return zero'\&. Otherwise, an error number will be returned to indicate the error'\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
