.TH "Mutex" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mutex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "int \fBlock\fP ()"
.br
.ti -1c
.RI "int \fBtryLock\fP ()"
.br
.ti -1c
.RI "int \fBunlock\fP ()"
.br
.ti -1c
.RI "int \fBdestroy\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mutex::Mutex ()"
.SH "Member Function Documentation"
.PP 
.SS "int Mutex::destroy ()"
.SS "int Mutex::lock ()"
.SS "int Mutex::tryLock ()"
.SS "int Mutex::unlock ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
