.TH "Include/System/Semaphore.h" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/System/Semaphore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <semaphore\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSemaphore\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
