.TH "Semaphore" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Semaphore\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemaphore\fP (char name[], unsigned int val)"
.br
.ti -1c
.RI "int \fBwait\fP ()"
.br
.ti -1c
.RI "int \fBpost\fP ()"
.br
.ti -1c
.RI "int \fBtryWait\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Semaphore::Semaphore (charname[], unsigned intval)"
.SH "Member Function Documentation"
.PP 
.SS "void Semaphore::close ()"
.SS "int Semaphore::post ()"
.SS "int Semaphore::tryWait ()"
.SS "int Semaphore::wait ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
