.TH "SocketErrors" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketErrors \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SocketErrors\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSOSUCC\fP = 1"
.br
.RI "\fISuccess'\&. \fP"
.ti -1c
.RI "static const int \fBSOCOPEN\fP = -1"
.br
.RI "\fICould not open Socket'\&. \fP"
.ti -1c
.RI "static const int \fBSONHOST\fP = -2"
.br
.RI "\fIHost not found'\&. \fP"
.ti -1c
.RI "static const int \fBSOCONN\fP = -3"
.br
.RI "\fICould not connect'\&. \fP"
.ti -1c
.RI "static const int \fBSOCLO\fP = -4"
.br
.RI "\fICould not close the connection'\&. \fP"
.ti -1c
.RI "static const int \fBSOEWRITE\fP = -5"
.br
.RI "\fICould not write to socket'\&. \fP"
.ti -1c
.RI "static const int \fBSOEREAD\fP = -6"
.br
.RI "\fICould not read from socket'\&. \fP"
.ti -1c
.RI "static const int \fBSOEMEM\fP = -7"
.br
.RI "\fICould not allocate mem'\&. \fP"
.ti -1c
.RI "static const int \fBSOEBIND\fP = -8"
.br
.RI "\fICould not bind socket'\&. \fP"
.ti -1c
.RI "static const int \fBSOELIST\fP = -9"
.br
.RI "\fICould not listen on socket'\&. \fP"
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const int \fBSocketErrors::SOCLO\fP = -4\fC [static]\fP"
.PP
Could not close the connection'\&. 
.SS "const int \fBSocketErrors::SOCONN\fP = -3\fC [static]\fP"
.PP
Could not connect'\&. 
.SS "const int \fBSocketErrors::SOCOPEN\fP = -1\fC [static]\fP"
.PP
Could not open Socket'\&. 
.SS "const int \fBSocketErrors::SOEBIND\fP = -8\fC [static]\fP"
.PP
Could not bind socket'\&. 
.SS "const int \fBSocketErrors::SOELIST\fP = -9\fC [static]\fP"
.PP
Could not listen on socket'\&. 
.SS "const int \fBSocketErrors::SOEMEM\fP = -7\fC [static]\fP"
.PP
Could not allocate mem'\&. 
.SS "const int \fBSocketErrors::SOEREAD\fP = -6\fC [static]\fP"
.PP
Could not read from socket'\&. 
.SS "const int \fBSocketErrors::SOEWRITE\fP = -5\fC [static]\fP"
.PP
Could not write to socket'\&. 
.SS "const int \fBSocketErrors::SONHOST\fP = -2\fC [static]\fP"
.PP
Host not found'\&. 
.SS "const int \fBSocketErrors::SOSUCC\fP = 1\fC [static]\fP"
.PP
Success'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
