.TH "Include/Socket/SocketErrors.h" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/Socket/SocketErrors.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocketErrors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
