.TH "Include/System/Thread.h" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/System/Thread.h \- 
.PP
A C++ \fBThread\fP Wrapper for the pthread lib You need to subclass it and redefine the run() method'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A C++ \fBThread\fP Wrapper for the pthread lib You need to subclass it and redefine the run() method'\&. 

A C++ \fBThread\fP Wrapper for the pthread lib'\&.
.PP
\fBAuthor:\fP
.RS 4
Ben D'\&. (BD), dbapps2@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
