.TH "Include/System/Types.h" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/System/Types.h \- 
.PP
\fBTypes\fP class'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTypes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTypes\fP class'\&. 

\fBVersion:\fP
.RS 4
1'\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
10/13/2011 09:28:55
.RE
.PP
\fBAuthor:\fP
.RS 4
Ben D'\&. (BD), dbapps2@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
