.TH "Types" 3 "Sun Oct 16 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Types \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBtoString\fP (int)"
.br
.RI "\fIConverts an int to a string'\&. \fP"
.ti -1c
.RI "static string \fBtoString\fP (char)"
.br
.RI "\fIConverts a char to a String'\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string Types::toString (inti)\fC [static]\fP"
.PP
Converts an int to a string'\&. \fBReturns:\fP
.RS 4
the int converted to string 
.RE
.PP

.SS "string Types::toString (charc)\fC [static]\fP"
.PP
Converts a char to a String'\&. \fBReturns:\fP
.RS 4
the converted to string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
