.TH "System/Types.cpp" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System/Types.cpp \- 
.PP
\fBTypes\fP class'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <System/Types\&.h>\fP
.br

.SH "Detailed Description"
.PP 
\fBTypes\fP class'\&. 

\fBVersion:\fP
.RS 4
1'\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
10/13/2011 09:28:55
.RE
.PP
\fBAuthor:\fP
.RS 4
Ben D'\&. (BD), dbapps2@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
