.TH "Types" 3 "Fri Oct 14 2011" "Version 0.3" "CPPWrappers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Types \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBtoString\fP (int)"
.br
.ti -1c
.RI "static string \fBtoString\fP (char)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string Types::toString (inti)\fC [static]\fP"
.SS "string Types::toString (charc)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CPPWrappers from the source code'\&.
